### ISSUE TITLE
Library / Package versions in requirements.txt

### ISSUE THREAD

**Issue by dasguptar** [IBM/gan-toolkit#4]
`requirements.txt` does not contain library/package versions.

This will lead to issues, as the codebase is built around PyTorch 0.3, but currently, the stable release is 0.4.1

Similar problems might crop up with other requirements as well, e.g. Keras.

**Comment by goodboyanush** [comment]
@panwarnaveen9 do you want to add `tensorflow-gpu` or only `tensorflow` 

it is tested to work on both, however, `gpu` version is what we suggest

**Comment by panwarnaveen9** [comment]
@goodboyanush we can write in readme that if you are using CUDA gpu 
install `tensorflow-gpu`
